Repository AY2122S2-CS2113-T11-3/tp, pull requests merged in 2022-04, with the labels that each got.

#216 Post ped changes
  MeetingJio.txt
  docs/UserGuide.md
  src/main/java/seedu/meetingjio/commands/AddMeetingCommand.java
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
  src/main/java/seedu/meetingjio/common/Messages.java
  src/main/java/seedu/meetingjio/parser/Parser.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
  src/main/java/seedu/meetingjio/ui/Ui.java
Labels: bug, documentation, priority.High, severity.High

#217 Editppp
  docs/UserGuide.md
  docs/team/ibrahimsharul.md
Labels: documentation

#218 Junit test addmeeting
  docs/AboutUs.md
  docs/images/ibrahimisramos.jpg
  docs/team/ibrahimisramos.md
  src/main/java/seedu/meetingjio/commands/AddMeetingCommand.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
  src/test/java/seedu/meetingjio/commands/AddMeetingTest.java
  src/test/java/seedu/meetingjio/commands/ParserTest.java
Labels: documentation, type.Junit

#219 Junit add meeting and delete
  MeetingJio.txt
  docs/UserGuide.md
  src/main/java/seedu/meetingjio/commands/ClearCommand.java
  src/main/java/seedu/meetingjio/parser/ParserArguments.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
  src/test/java/seedu/meetingjio/commands/DeleteCommandTest.java
  src/test/java/seedu/meetingjio/commands/ParserTest.java
  text-ui-test/sample_commands.txt
Labels: bug, documentation, help wanted

#220 Rectify Free Command
  docs/UserGuide.md
  src/main/java/seedu/meetingjio/commands/FreeCommand.java
  src/main/java/seedu/meetingjio/commands/ListCommand.java
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
  src/main/java/seedu/meetingjio/exceptions/EmptyMasterTimetableException.java
  src/main/java/seedu/meetingjio/parser/ParserHelperMethods.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
  src/main/java/seedu/meetingjio/timetables/Timetable.java
  src/test/java/seedu/meetingjio/commands/FreeCommandTest.java
Labels: documentation, priority.High, type.Junit

#221 Fill up ppp
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/angyongming.md
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
Labels: documentation

#224 Edit dg and sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/AddMeetingCommandSequence.png
  docs/diagrams/AddMeetingCommandSequence.puml
  docs/diagrams/AddMeetingObjectDiagram.puml
  docs/diagrams/ClearCommandSequenceDiagram.png
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/DeleteCommandSequenceDiagram.png
  docs/diagrams/DeleteCommandSequenceDiagram.puml
  docs/images/DeleteCommandSequenceDiagram.png
  docs/team/ibrahimisramos.md
Labels: documentation

#231 Refactored free command to avoid cyclic dependency
  src/main/java/seedu/meetingjio/commands/FreeCommand.java
  src/main/java/seedu/meetingjio/timetables/Timetable.java
Labels: priority.Medium

#234 Code quality check for code
  docs/diagrams/ClearCommandSequenceDiagram.puml
  src/main/java/seedu/meetingjio/commands/AddMeetingCommand.java
  src/main/java/seedu/meetingjio/commands/ClearCommand.java
  src/main/java/seedu/meetingjio/commands/DeleteCommand.java
  src/main/java/seedu/meetingjio/common/Messages.java
  src/main/java/seedu/meetingjio/parser/Parser.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
  src/main/java/seedu/meetingjio/timetables/Timetable.java
  src/test/java/seedu/meetingjio/parser/ParserTest.java
Labels: documentation

#237 Add Junit for ParserLocalData and update user guide
  docs/UserGuide.md
  docs/team/lihao.md
  src/main/java/seedu/meetingjio/MeetingJio.java
  src/main/java/seedu/meetingjio/parser/ParserLocalData.java
  src/main/java/seedu/meetingjio/storage/StorageFile.java
  src/test/java/seedu/meetingjio/parser/ParserLocalDataTest.java
Labels: bug, documentation, type.Junit

#240 edit junit testing for delete command
  src/test/java/seedu/meetingjio/commands/DeleteCommandTest.java
Labels: type.Junit

#243 Add class diagram for Ui and Event
  docs/diagrams/EventClassDiagram.png
  docs/diagrams/EventClassDiagram.puml
  docs/diagrams/FreeCommandSequenceDiagram.png
  docs/diagrams/FreeCommandSequenceDiagram.puml
  docs/diagrams/ListCommandSequenceDiagram.png
  docs/diagrams/UiClassDiagram.png
  docs/diagrams/UiClassDiagram.puml
Labels: documentation, priority.Medium

#242 Add class diagram to dg
  MeetingJio.txt
  docs/DeveloperGuide.md
  docs/diagrams/TimetableClassDiagram.puml
  src/main/java/seedu/meetingjio/common/Messages.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
  src/test/java/seedu/meetingjio/parser/ParserTest.java
Labels: documentation

#246 Update appendix in developer guide
  docs/DeveloperGuide.md
Labels: documentation

#248 Add command class diagram and storage class diagram
  docs/DeveloperGuide.md
  docs/diagrams/CommandClassDiagram1.puml
  docs/diagrams/CommandClassDiagram2.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/CommandClassDiagram1.png
  docs/images/CommandClassDiagram2.png
  docs/images/StorageClassDiagram.png
Labels: documentation

#249 Update DG
  docs/DeveloperGuide.md
Labels: documentation

#251 User guide Editing
  docs/UserGuide.md
  src/main/java/seedu/meetingjio/MeetingJio.java
  src/main/java/seedu/meetingjio/ui/Ui.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/input.txt
  text-ui-test/sample_commands.txt
Labels: documentation

#252 Edit DG features
  docs/DeveloperGuide.md
  docs/diagrams/DeleteCommandSequenceDiagram.png
  docs/diagrams/DeleteCommandSequenceDiagram.puml
  docs/images/AddCommandSequenceDiagram.png
  docs/images/AddLessonCommandSequence.png
  docs/images/AddLessonCommandSequenceDiagram.png
  docs/images/AddMeetingCommandSequence.png
  docs/images/AddUserCommandSequenceDiagram.png
  docs/images/ClearCommandSequenceDiagram.png
  docs/images/CommandSequenceDiagram.png
  docs/images/DeleteCommandSequenceDiagram.png
  docs/images/EditCommandSequenceDiagram.png
  docs/images/EventClassDiagram.png
  docs/images/FreeCommandSequenceDiagram.png
  docs/images/ListCommandSequenceDiagram.png
  docs/images/LoadSequenceDiagram.png
  docs/images/ParserClassDiagram.png
  docs/images/SaveSequenceDiagram.png
  docs/images/UiClassDiagram.png
Labels: documentation

#254 Edit add_user description to be more specific
  docs/UserGuide.md
Labels: documentation

#256 Terminate sequence diagram for list command and free command
  docs/diagrams/FreeCommandSequenceDiagram.puml
  docs/diagrams/ListCommandSequenceDiagram.puml
  docs/images/FreeCommandSequenceDiagram.png
  docs/images/ListCommandSequenceDiagram.png
Labels: documentation, priority.Medium

#259 Edit dg for clear, delete and add_meeting
  docs/DeveloperGuide.md
  docs/diagrams/AddLessonCommandSequence.puml
  docs/diagrams/AddMeetingCommandSequence.puml
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/DeleteCommandSequenceDiagram.puml
  docs/images/TimetableClassDiagram.png
  src/main/java/seedu/meetingjio/commands/ClearCommand.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
  src/main/java/seedu/meetingjio/timetables/Timetable.java
Labels: documentation

#258 Fix error found in loading data
  src/main/java/seedu/meetingjio/MeetingJio.java
  src/main/java/seedu/meetingjio/parser/ParserLocalData.java
Labels: bug, priority.High

#260 Edit dg clear
  docs/DeveloperGuide.md
  docs/images/ClearCommandSequenceDiagram.png
  docs/images/DeleteCommandSequenceDiagram.png
  docs/team/ibrahimisramos.md
Labels: documentation

#265 Update AboutUs
  docs/AboutUs.md
  docs/images/lihao-infosec.jpg
  docs/team/lihao-infosec.md
Labels: documentation

#264 Change test method name
  docs/images/AddMeetingCommandSequence.png
  src/test/java/seedu/meetingjio/commands/AddMeetingCommandTest.java
  src/test/java/seedu/meetingjio/commands/ClearCommandTest.java
Labels: documentation

#267 rename junit testing methods for list and free command
  docs/DeveloperGuide.md
  src/test/java/seedu/meetingjio/commands/FreeCommandTest.java
  src/test/java/seedu/meetingjio/commands/ListCommandTest.java
Labels: type.Junit

#268 All test works
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/meetingjio/MeetingJio.java
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
  src/main/java/seedu/meetingjio/ui/Ui.java
Labels: bug, documentation

#269 Edit PPP
  docs/team/lihao-infosec.md
Labels: documentation

#272 Edit free error message
  docs/team/ibrahimisramos.md
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
Labels: documentation

#271 fix styling
  docs/UserGuide.md
  docs/diagrams/CommandClassDiagram1.puml
  docs/diagrams/CommandClassDiagram2.puml
  docs/images/CommandClassDiagram1.png
  docs/images/CommandClassDiagram2.png
  docs/team/ibrahimisramos.md
  docs/team/lihao-infosec.md
Labels: documentation

#276 Edit sq for delete command activation bar
  docs/diagrams/DeleteCommandSequenceDiagram.puml
  docs/images/DeleteCommandSequenceDiagram.png
Labels: documentation

#281 Edit save and load sequence diagram
  docs/diagrams/LoadSequenceDiagram.puml
  docs/diagrams/SaveSequenceDiagram.puml
  docs/images/LoadSequenceDiagram.png
  docs/images/SaveSequenceDiagram.png
Labels: documentation

#279 Edit sequence diagrams
  docs/diagrams/AddMeetingCommandSequence.puml
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/DeleteCommandSequenceDiagram.puml
  docs/images/AddMeetingCommandSequence.png
  docs/images/ClearCommandSequenceDiagram.png
  docs/images/DeleteCommandSequenceDiagram.png
Labels: documentation

#282 update user guide and load sequence diagram
  docs/UserGuide.md
  docs/diagrams/LoadSequenceDiagram.puml
  docs/images/LoadSequenceDiagram.png
Labels: documentation
