Repository AY2122S2-CS2113-T11-3/tp, pull requests merged in 2022-03, with the labels that each got.

#50 Change JUnit Test for assert
  src/main/java/seedu/duke/Parser.java
  src/test/java/seedu/duke/commands/DeleteCommandTest.java
  src/test/java/seedu/duke/commands/ParserTest.java
Labels: priority.Medium, type.junit, type.logging

#71 Javadoc delete command and related
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/commands/ClearCommand.java
  src/main/java/seedu/duke/commands/DeleteCommand.java
  src/test/java/seedu/duke/commands/DeleteCommandTest.java
  src/test/java/seedu/duke/commands/ParserTest.java
Labels: documentation

#83 Add Javadoc for add command
  src/main/java/META-INF/MANIFEST.MF
  src/main/java/seedu/duke/commands/AddCommand.java
Labels: documentation, priority.Low

#91 Incorporate assertions and more JUnit testing
  src/main/java/seedu/meetingjio/commands/ListCommand.java
  src/main/java/seedu/meetingjio/events/Event.java
  src/test/java/seedu/meetingjio/commands/AddCommandTest.java
Labels: priority.Medium, type.Junit

#97 Add assert for Delete Command and Clear Command
  src/main/java/seedu/meetingjio/commands/ClearCommand.java
  src/main/java/seedu/meetingjio/commands/DeleteCommand.java
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
Labels: priority.Low

#106 Add Clearcommand sequence diagram
  docs/DeleteCommand.drawio
  docs/DeveloperGuide.md
  docs/diagrams/ClearCommandSequenceDiagram.png
  docs/diagrams/ClearCommandSequenceDiagram.puml
  docs/diagrams/style.puml
Labels: documentation

#108 Update ListCommand to specify which timetable to be listed out
  src/main/java/seedu/meetingjio/Parser.java
  src/main/java/seedu/meetingjio/commands/ListCommand.java
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
  src/main/java/seedu/meetingjio/common/Messages.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
  src/test/java/seedu/meetingjio/commands/ListCommandTest.java
Labels: priority.High, type.Junit

#116 Edit list command
  src/main/java/seedu/meetingjio/commands/ClearCommand.java
  src/main/java/seedu/meetingjio/commands/ListCommand.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
Labels: priority.Medium

#117 Improve user interface by sorting the timetables
  src/main/java/seedu/meetingjio/Parser.java
  src/main/java/seedu/meetingjio/commands/ListCommand.java
  src/main/java/seedu/meetingjio/events/Event.java
  src/main/java/seedu/meetingjio/timetables/Timetable.java
Labels: enhancement, priority.High

#118 rectify coding style errors and add junit for list sort
  src/main/java/seedu/meetingjio/events/Event.java
  src/main/java/seedu/meetingjio/timetables/Timetable.java
  src/test/java/seedu/meetingjio/commands/ListCommandTest.java
Labels: type.Junit

#121 Implement function to search for common timeslots
  src/main/java/seedu/meetingjio/Parser.java
  src/main/java/seedu/meetingjio/commands/FreeCommand.java
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
  src/main/java/seedu/meetingjio/common/Messages.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
  src/main/java/seedu/meetingjio/timetables/Timetable.java
Labels: enhancement, priority.High

#126 Addmeeting and delete command branch
  src/main/java/seedu/meetingjio/Parser.java
  src/main/java/seedu/meetingjio/commands/AddMeetingCommand.java
  src/main/java/seedu/meetingjio/commands/DeleteCommand.java
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
  src/main/java/seedu/meetingjio/events/Meeting.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
  src/main/java/seedu/meetingjio/timetables/Timetable.java
  text-ui-test/sample_commands.txt
Labels: priority.High, type.Story, severity.Medium

#132 Filter free time slots based on duration
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
Labels: enhancement, priority.High

#134 Refactor, add JavaDoc, JUnit testing and update user guide for free command
  docs/UserGuide.md
  docs/team/angyongming.md
  src/main/java/seedu/meetingjio/commands/FreeCommand.java
  src/main/java/seedu/meetingjio/events/Event.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
  src/main/java/seedu/meetingjio/timetables/Timetable.java
  src/test/java/seedu/meetingjio/commands/FreeCommandTest.java
Labels: documentation, priority.Medium, type.Junit

#138 Junit testing clear and user guide
  docs/UserGuide.md
  src/main/java/seedu/meetingjio/commands/ClearCommand.java
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
  src/test/java/seedu/meetingjio/commands/ClearCommandTest.java
  src/test/java/seedu/meetingjio/commands/DeleteCommandTest.java
  text-ui-test/sample_commands.txt
Labels: documentation, severity.Medium, type.Junit

#139 Fix Add_meeting to properly save the meeting title
  src/main/java/seedu/meetingjio/Parser.java
  text-ui-test/sample_commands.txt
Labels: priority.High, severity.High

#140 Refactor execute to UI and refactor parser
  src/main/java/seedu/meetingjio/MeetingJio.java
  src/main/java/seedu/meetingjio/Parser.java
  src/main/java/seedu/meetingjio/commands/ClearCommand.java
  src/main/java/seedu/meetingjio/commands/Command.java
  src/main/java/seedu/meetingjio/commands/DeleteCommand.java
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
  src/main/java/seedu/meetingjio/parser/Parser.java
  src/main/java/seedu/meetingjio/parser/ParserArguments.java
  src/main/java/seedu/meetingjio/parser/ParserHelperMethods.java
  src/main/java/seedu/meetingjio/ui/TextUi.java
  src/main/java/seedu/meetingjio/ui/Ui.java
Labels: priority.High, severity.Medium

#145 Delete user once meeting added
  docs/UserGuide.md
  src/main/java/seedu/meetingjio/commands/AddLessonCommand.java
  src/main/java/seedu/meetingjio/commands/AddMeetingCommand.java
  src/main/java/seedu/meetingjio/commands/ClearCommand.java
  src/main/java/seedu/meetingjio/commands/DeleteCommand.java
  src/main/java/seedu/meetingjio/common/Messages.java
  src/main/java/seedu/meetingjio/parser/ParserArguments.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
  src/test/java/seedu/meetingjio/commands/ClearCommandTest.java
Labels: documentation, enhancement, priority.Medium

#148 Add save and Load function as well as exception handlings
  src/main/java/seedu/meetingjio/MeetingJio.java
  src/main/java/seedu/meetingjio/commands/Command.java
  src/main/java/seedu/meetingjio/commands/ExitCommand.java
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
  src/main/java/seedu/meetingjio/common/Messages.java
  src/main/java/seedu/meetingjio/exceptions/DuplicateEventException.java
  src/main/java/seedu/meetingjio/exceptions/IncorrectIndexException.java
  src/main/java/seedu/meetingjio/exceptions/InvalidDayException.java
  src/main/java/seedu/meetingjio/exceptions/InvalidEventTypeException.java
  src/main/java/seedu/meetingjio/exceptions/InvalidModeException.java
  src/main/java/seedu/meetingjio/exceptions/InvalidTimeException.java
  src/main/java/seedu/meetingjio/exceptions/MissingParameterException.java
  src/main/java/seedu/meetingjio/exceptions/MissingValueException.java
  src/main/java/seedu/meetingjio/exceptions/OverlappingEventException.java
  src/main/java/seedu/meetingjio/exceptions/TimetableNotFoundException.java
  src/main/java/seedu/meetingjio/parser/ParserLocalData.java
  src/main/java/seedu/meetingjio/storage/StorageFile.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#151 Add JavDoc for save and load function
  src/main/java/seedu/meetingjio/MeetingJio.java
  src/main/java/seedu/meetingjio/parser/ParserLocalData.java
  src/main/java/seedu/meetingjio/storage/StorageFile.java
Labels: documentation

#156 Add save and load sequence diagram to DG
  docs/DeveloperGuide.md
  docs/diagrams/LoadSequenceDiagram.png
  docs/diagrams/LoadSequenceDiagram.puml
  docs/diagrams/SaveSequenceDiagram.png
  docs/diagrams/SaveSequenceDiagram.puml
  src/main/java/seedu/meetingjio/MeetingJio.java
Labels: documentation

#158 Change AddLessonCommand
  MeetingJio.txt
  src/main/java/seedu/meetingjio/commands/AddLessonCommand.java
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
  src/test/java/seedu/meetingjio/commands/ClearCommandTest.java
  src/test/java/seedu/meetingjio/commands/FreeCommandTest.java
  src/test/java/seedu/meetingjio/commands/ListCommandTest.java
Labels: priority.High

#162 Create AddUserCommand
  src/main/java/seedu/meetingjio/commands/AddLessonCommand.java
  src/main/java/seedu/meetingjio/commands/AddUserCommand.java
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
  src/main/java/seedu/meetingjio/exceptions/DuplicateTimetableException.java
  src/main/java/seedu/meetingjio/parser/Parser.java
  src/main/java/seedu/meetingjio/parser/ParserHelperMethods.java
  src/main/java/seedu/meetingjio/parser/ParserLocalData.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
  src/main/java/seedu/meetingjio/timetables/Timetable.java
  src/main/java/seedu/meetingjio/ui/Ui.java
  text-ui-test/sample_commands.txt
Labels: priority.High

#167 Add error handle for duplicate user name
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
  src/main/java/seedu/meetingjio/parser/ParserLocalData.java
  src/main/java/seedu/meetingjio/storage/StorageFile.java
Labels: enhancement, priority.High

#170 update list command to specify list lesson or list meeting
  docs/UserGuide.md
  docs/diagrams/ListCommandSequenceDiagram.png
  docs/diagrams/ListCommandSequenceDiagram.puml
  src/main/java/seedu/meetingjio/commands/ListCommand.java
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
  src/main/java/seedu/meetingjio/common/Messages.java
  src/main/java/seedu/meetingjio/parser/Parser.java
  src/main/java/seedu/meetingjio/storage/StorageFile.java
  src/main/java/seedu/meetingjio/timetables/MasterTimetable.java
  src/main/java/seedu/meetingjio/timetables/Timetable.java
  src/test/java/seedu/meetingjio/commands/ClearCommandTest.java
  src/test/java/seedu/meetingjio/commands/ListCommandTest.java
Labels: enhancement, priority.High, type.Junit

#175 Update no events message
  src/main/java/seedu/meetingjio/storage/StorageFile.java
Labels: bug

#176 New changes edit error message
  .gitignore
  MeetingJio.txt
  src/main/java/seedu/meetingjio/common/ErrorMessages.java
Labels: documentation
